use crate::map_element;
use map_element::MapElementKind;

pub const ROW_MAX_LENGTH: usize = 23;
pub const ROW1: [MapElementKind; ROW_MAX_LENGTH] = [
    MapElementKind::ZELDA, 
    MapElementKind::HCL, 
    MapElementKind::HCD, 
    MapElementKind::HCR, 
    MapElementKind::EP, 
    MapElementKind::DPL, 
    MapElementKind::DPD, 
    MapElementKind::DPR,
    MapElementKind::DPU, 
    MapElementKind::TH, 
    MapElementKind::AT,
    MapElementKind::PD,
    MapElementKind::SP,
    MapElementKind::SW,
    MapElementKind::TT,
    MapElementKind::IP,
    MapElementKind::MM,
    MapElementKind::TRL,
    MapElementKind::TRD,
    MapElementKind::TRR,
    MapElementKind::TRU,
    MapElementKind::GT,
    MapElementKind::GANON
];

pub const ROW2: [MapElementKind; ROW_MAX_LENGTH] = [
    MapElementKind::SPECU, 
    MapElementKind::PARAU,
    MapElementKind::DARK, 
    MapElementKind::OLDMANU, 
    MapElementKind::SUPERBUNNYU, 
    MapElementKind::BUMPERU, 
    MapElementKind::SPIRALU, 
    MapElementKind::HYPE, 
    MapElementKind::MIRESHED, 
    MapElementKind::LIBRARY, 
    MapElementKind::SICKKID, 
    MapElementKind::AGINAH,
    MapElementKind::DAM,
    MapElementKind::ICEROD,
    MapElementKind::HAMMERPEGS,
    MapElementKind::SAHA,
    MapElementKind::POTION,
    MapElementKind::BLANK,
    MapElementKind::BOOTS,
    MapElementKind::GLOVE,
    MapElementKind::FLIPPERS,
    MapElementKind::SWORD,
    MapElementKind::POWDER,
];

pub const ROW3: [MapElementKind; ROW_MAX_LENGTH] = [
    MapElementKind::SPECM, 
    MapElementKind::PARAM,
    MapElementKind::RESCUE, 
    MapElementKind::OLDMANL, 
    MapElementKind::SUPERBUNNYL, 
    MapElementKind::BUMPERL, 
    MapElementKind::SPIRALL, 
    MapElementKind::MMC, 
    MapElementKind::WATERFALL, 
    MapElementKind::MIMIC, 
    MapElementKind::CHESTGAME, 
    MapElementKind::CHICKEN,
    MapElementKind::BONK,
    MapElementKind::BREWERY,
    MapElementKind::CHECKERBOARD,
    MapElementKind::SMITH,
    MapElementKind::UPGRADEFAIRY,
    MapElementKind::BLANK,
    MapElementKind::MIRROR,
    MapElementKind::HAMMER,
    MapElementKind::BOW,
    MapElementKind::BOMBOS,
    MapElementKind::BIGKEY,
];

pub const ROW4: [MapElementKind; ROW_MAX_LENGTH] = [
    MapElementKind::SPECL, 
    MapElementKind::PARAL,
    MapElementKind::DESCENT, 
    MapElementKind::FAIRY, 
    MapElementKind::BROTHERS, 
    MapElementKind::ELDER, 
    MapElementKind::HOOKSHOT, 
    MapElementKind::BLINDS, 
    MapElementKind::PFAIRY, 
    MapElementKind::SPIKE, 
    MapElementKind::CAVE45, 
    MapElementKind::GYL,
    MapElementKind::CHOUSE,
    MapElementKind::KINGSTOMB,
    MapElementKind::BLANK,
    MapElementKind::REDBOMB,
    MapElementKind::SHOP,
    MapElementKind::BLANK,
    MapElementKind::MEARL,
    MapElementKind::FIREROD,
    MapElementKind::LAMP,
    MapElementKind::SOMARIA,
    MapElementKind::SMALLKEY,
];