use eframe::egui::{self, Pos2, Vec2};
use crate::egui::ImageSource;
use uuid::Uuid;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct MapElement {
    pub pos: Pos2,
    pub size: Option<Vec2>,
    pub kind: MapElementKind,
    pub id: Uuid,
    pub checked: bool
}

#[allow(unused)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MapElementKind {
    ENTRANCE,
    ITEM,
    ZELDA,
    HCL,
    HCD,
    HCR,
    EP,
    DPL,
    DPD,
    DPR,
    DPU,
    TH,
    AT,
    PD,
    SP,
    SW,
    TT,
    IP,
    MM,
    TRL,
    TRD,
    TRR,
    TRU,
    GT,
    GANON,
    SPECU,
    SPECM,
    SPECL,
    PARAU,
    PARAM,
    PARAL,
    DARK,
    RESCUE,
    DESCENT,
    OLDMANU,
    OLDMANL,
    FAIRY,
    SUPERBUNNYU,
    SUPERBUNNYL,
    BROTHERS,
    BUMPERU,
    BUMPERL,
    ELDER,
    SPIRALU,
    SPIRALL,
    HOOKSHOT,
    HYPE,
    MMC,
    BLINDS,
    MIRESHED,
    WATERFALL,
    PFAIRY,
    LIBRARY,
    MIMIC,
    SPIKE,
    SICKKID,
    CHESTGAME,
    CAVE45,
    AGINAH,
    CHICKEN,
    GYL,
    DAM,
    BONK,
    CHOUSE,
    ICEROD,
    BREWERY,
    KINGSTOMB,
    HAMMERPEGS,
    CHECKERBOARD,
    SAHA,
    SMITH,
    REDBOMB,
    POTION,
    UPGRADEFAIRY,
    SHOP,
    BOOTS,
    MIRROR,
    MEARL,
    GLOVE,
    HAMMER,
    FIREROD,
    FLIPPERS,
    BOW,
    LAMP,
    SWORD,
    BOMBOS,
    SOMARIA,
    POWDER,
    BIGKEY,
    SMALLKEY,
    BOMBOSTABLET,
    ETHERTABLET,
    BOTTLEMERCHANT,
    DESERTLEDGE,
    FLOATINGISLAND,
    HOBO,
    KINGZORA,
    ZORALEDGE,
    LAKEHYLIAISLAND,
    PED,
    MAZERACE,
    MUSHROOM,
    OLDMAN,
    PURPLECHEST,
    SPECROCK,
    SUNKENTREASURE,
    BUMPERCAVELEDGE,
    CATFISH,
    DIGGAME,
    STUMPY,
    FLUTESPOT,
    PYRAMID,
    BLANK
}


#[allow(unused)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MapElementCategory {
    HC,
    EP,
    DP,
    TH,
    AT,
    PD,
    SP,
    SW,
    TT,
    IP,
    MM,
    TR,
    GT,
    GANON,
    SPEC,
    PARA,
    DARKCAVE,
    OLDMAN,
    FAIRY,
    SUPERBUNNY,
    BROTHERS,
    BUMPER,
    ELDER,
    SPIRAL,
    HOOKSHOT,
    HYPE,
    MMC,
    BLINDS,
    MIRESHED,
    WATERFALL,
    PFAIRY,
    LIBRARY,
    MIMIC,
    SPIKE,
    SICKKID,
    CHESTGAME,
    CAVE45,
    AGINAH,
    CHICKEN,
    GYL,
    DAM,
    BONK,
    CHOUSE,
    ICEROD,
    BREWERY,
    KINGSTOMB,
    HAMMERPEGS,
    CHECKERBOARD,
    SAHA,
    SMITH,
    REDBOMB,
    POTION,
    UPGRADEFAIRY,
    SHOP,
    BOOTS,
    MIRROR,
    MEARL,
    GLOVE,
    HAMMER,
    FIREROD,
    FLIPPERS,
    BOW,
    LAMP,
    SWORD,
    BOMBOS,
    SOMARIA,
    POWDER,
    BIGKEY,
    SMALLKEY,
    BLANK
}

pub fn str_to_kind(kind: &str) -> MapElementKind {
    match kind {
        "ENTRANCE" => MapElementKind::ENTRANCE,
        "ITEM" => MapElementKind::ITEM,
        "ZELDA" => MapElementKind::ZELDA,
        "HCL" => MapElementKind::HCL,
        "HCD" => MapElementKind::HCD,
        "HCR" => MapElementKind::HCR,
        "EP" => MapElementKind::EP,
        "DPL" => MapElementKind::DPL,
        "DPD" => MapElementKind::DPD,
        "DPR" => MapElementKind::DPR,
        "DPU" => MapElementKind::DPU,
        "TH" => MapElementKind::TH,
        "AT" => MapElementKind::AT,
        "PD" => MapElementKind::PD,
        "SP" => MapElementKind::SP,
        "SW" => MapElementKind::SW,
        "TT" => MapElementKind::TT,
        "IP" => MapElementKind::IP,
        "MM" => MapElementKind::MM,
        "TRL" => MapElementKind::TRL,
        "TRD" => MapElementKind::TRD,
        "TRR" => MapElementKind::TRR,
        "TRU" => MapElementKind::TRU,
        "GT" => MapElementKind::GT,
        "GANON" => MapElementKind::GANON,
        "SPECU" => MapElementKind::SPECU,
        "SPECM" => MapElementKind::SPECM,
        "SPECL" => MapElementKind::SPECL,
        "PARAU" => MapElementKind::PARAU,
        "PARAM" => MapElementKind::PARAM,
        "PARAL" => MapElementKind::PARAL,
        "DARK" => MapElementKind::DARK,
        "RESCUE" => MapElementKind::RESCUE,
        "DESCENT" => MapElementKind::DESCENT,
        "OLDMANU" => MapElementKind::OLDMANU,
        "OLDMANL" => MapElementKind::OLDMANL,
        "FAIRY" => MapElementKind::FAIRY,
        "SUPERBUNNYU" => MapElementKind::SUPERBUNNYU,
        "SUPERBUNNYL" => MapElementKind::SUPERBUNNYL,
        "BROTHERS" => MapElementKind::BROTHERS,
        "BUMPERU" => MapElementKind::BUMPERU,
        "BUMPERL" => MapElementKind::BUMPERL,
        "ELDER" => MapElementKind::ELDER,
        "SPIRALU" => MapElementKind::SPIRALU,
        "SPIRALL" => MapElementKind::SPIRALL,
        "HOOKSHOT" => MapElementKind::HOOKSHOT,
        "HYPE" => MapElementKind::HYPE,
        "MMC" => MapElementKind::MMC,
        "BLINDS" => MapElementKind::BLINDS,
        "MIRESHED" => MapElementKind::MIRESHED,
        "WATERFALL" => MapElementKind::WATERFALL,
        "PFAIRY" => MapElementKind::PFAIRY,
        "LIBRARY" => MapElementKind::LIBRARY,
        "MIMIC" => MapElementKind::MIMIC,
        "SPIKE" => MapElementKind::SPIKE,
        "SICKKID" => MapElementKind::SICKKID,
        "CHESTGAME" => MapElementKind::CHESTGAME,
        "CAVE45" => MapElementKind::CAVE45,
        "AGINAH" => MapElementKind::AGINAH,
        "CHICKEN" => MapElementKind::CHICKEN,
        "GYL" => MapElementKind::GYL,
        "DAM" => MapElementKind::DAM,
        "BONK" => MapElementKind::BONK,
        "CHOUSE" => MapElementKind::CHOUSE,
        "ICEROD" => MapElementKind::ICEROD,
        "BREWERY" => MapElementKind::BREWERY,
        "KINGSTOMB" => MapElementKind::KINGSTOMB,
        "HAMMERPEGS" => MapElementKind::HAMMERPEGS,
        "CHECKERBOARD" => MapElementKind::CHECKERBOARD,
        "SAHA" => MapElementKind::SAHA,
        "SMITH" => MapElementKind::SMITH,
        "REDBOMB" => MapElementKind::REDBOMB,
        "POTION" => MapElementKind::POTION,
        "UPGRADEFAIRY" => MapElementKind::UPGRADEFAIRY,
        "SHOP" => MapElementKind::SHOP,
        "BOOTS" => MapElementKind::BOOTS,
        "MIRROR" => MapElementKind::MIRROR,
        "MEARL" => MapElementKind::MEARL,
        "GLOVE" => MapElementKind::GLOVE,
        "HAMMER" => MapElementKind::HAMMER,
        "FIREROD" => MapElementKind::FIREROD,
        "FLIPPERS" => MapElementKind::FLIPPERS,
        "BOW" => MapElementKind::BOW,
        "LAMP" => MapElementKind::LAMP,
        "SWORD" => MapElementKind::SWORD,
        "BOMBOS" => MapElementKind::BOMBOS,
        "SOMARIA" => MapElementKind::SOMARIA,
        "POWDER" => MapElementKind::POWDER,
        "BIGKEY" => MapElementKind::BIGKEY,
        "SMALLKEY" => MapElementKind::SMALLKEY,
        "BLANK" => MapElementKind::BLANK,
        _ => panic!("Unrecognized icon.")
    }
}

#[allow(unused)]
pub fn kind_to_str(kind: &MapElementKind) -> &str {
    match kind {
        MapElementKind::ENTRANCE => "ENTRANCE",
        MapElementKind::ITEM => "ITEM",
        MapElementKind::ZELDA => "ZELDA",
        MapElementKind::HCL => "HCL",
        MapElementKind::HCD => "HCD",
        MapElementKind::HCR => "HCR",
        MapElementKind::EP => "EP",
        MapElementKind::DPL => "DPL",
        MapElementKind::DPD => "DPD",
        MapElementKind::DPR => "DPR",
        MapElementKind::DPU => "DPU",
        MapElementKind::TH => "TH",
        MapElementKind::AT => "AT",
        MapElementKind::PD => "PD",
        MapElementKind::SP => "SP",
        MapElementKind::SW => "SW",
        MapElementKind::TT => "TT",
        MapElementKind::IP => "IP",
        MapElementKind::MM => "MM",
        MapElementKind::TRL => "TRL",
        MapElementKind::TRD => "TRD",
        MapElementKind::TRR => "TRR",
        MapElementKind::TRU => "TRU",
        MapElementKind::GT => "GT",
        MapElementKind::GANON => "GANON",
        MapElementKind::SPECU => "SPECU",
        MapElementKind::SPECM => "SPECM",
        MapElementKind::SPECL => "SPECL",
        MapElementKind::PARAU => "PARAU",
        MapElementKind::PARAM => "PARAM",
        MapElementKind::PARAL => "PARAL",
        MapElementKind::DARK => "DARK",
        MapElementKind::RESCUE => "RESCUE",
        MapElementKind::DESCENT => "DESCENT",
        MapElementKind::OLDMANU => "OLDMANU",
        MapElementKind::OLDMANL => "OLDMANL",
        MapElementKind::FAIRY => "FAIRY",
        MapElementKind::SUPERBUNNYU => "SUPERBUNNYU",
        MapElementKind::SUPERBUNNYL => "SUPERBUNNYL",
        MapElementKind::BROTHERS => "BROTHERS",
        MapElementKind::BUMPERU => "BUMPERU",
        MapElementKind::BUMPERL => "BUMPERL",
        MapElementKind::ELDER => "ELDER",
        MapElementKind::SPIRALU => "SPIRALU",
        MapElementKind::SPIRALL => "SPIRALL",
        MapElementKind::HOOKSHOT => "HOOKSHOT",
        MapElementKind::HYPE => "HYPE",
        MapElementKind::MMC => "MMC",
        MapElementKind::BLINDS => "BLINDS",
        MapElementKind::MIRESHED => "MIRESHED",
        MapElementKind::WATERFALL => "WATERFALL",
        MapElementKind::PFAIRY => "PFAIRY",
        MapElementKind::LIBRARY => "LIBRARY",
        MapElementKind::MIMIC => "MIMIC",
        MapElementKind::SPIKE => "SPIKE",
        MapElementKind::SICKKID => "SICKKID",
        MapElementKind::CHESTGAME => "CHESTGAME",
        MapElementKind::CAVE45 => "CAVE45",
        MapElementKind::AGINAH => "AGINAH",
        MapElementKind::CHICKEN => "CHICKEN",
        MapElementKind::GYL => "GYL",
        MapElementKind::DAM => "DAM",
        MapElementKind::BONK => "BONK",
        MapElementKind::CHOUSE => "CHOUSE",
        MapElementKind::ICEROD => "ICEROD",
        MapElementKind::BREWERY => "BREWERY",
        MapElementKind::KINGSTOMB => "KINGSTOMB",
        MapElementKind::HAMMERPEGS => "HAMMERPEGS",
        MapElementKind::CHECKERBOARD => "CHECKERBOARD",
        MapElementKind::SAHA => "SAHA",
        MapElementKind::SMITH => "SMITH",
        MapElementKind::REDBOMB => "REDBOMB",
        MapElementKind::POTION => "POTION",
        MapElementKind::UPGRADEFAIRY => "UPGRADEFAIRY",
        MapElementKind::SHOP => "SHOP",
        MapElementKind::BOOTS => "BOOTS",
        MapElementKind::MIRROR => "MIRROR",
        MapElementKind::MEARL => "MEARL",
        MapElementKind::GLOVE => "GLOVE",
        MapElementKind::HAMMER => "HAMMER",
        MapElementKind::FIREROD => "FIREROD",
        MapElementKind::FLIPPERS => "FLIPPERS",
        MapElementKind::BOW => "BOW",
        MapElementKind::LAMP => "LAMP",
        MapElementKind::SWORD => "SWORD",
        MapElementKind::BOMBOS => "BOMBOS",
        MapElementKind::SOMARIA => "SOMARIA",
        MapElementKind::POWDER => "POWDER",
        MapElementKind::BIGKEY => "BIGKEY",
        MapElementKind::SMALLKEY => "SMALLKEY",
        MapElementKind::BLANK => "BLANK",
        MapElementKind::BOMBOSTABLET => "BOMBOSTABLET",
        MapElementKind::ETHERTABLET => "ETHERTABLET",
        MapElementKind::BOTTLEMERCHANT => "BOTTLEMERCHANT",
        MapElementKind::DESERTLEDGE => "DESERTLEDGE",
        MapElementKind::FLOATINGISLAND => "FLOATINGISLAND",
        MapElementKind::HOBO => "HOBO",
        MapElementKind::KINGZORA => "KINGZORA",
        MapElementKind::ZORALEDGE => "ZORALEDGE",
        MapElementKind::LAKEHYLIAISLAND => "LAKEHYLIAISLAND",
        MapElementKind::PED => "PED",
        MapElementKind::MAZERACE => "MAZERACE",
        MapElementKind::MUSHROOM => "MUSHROOM",
        MapElementKind::OLDMAN => "OLDMAN",
        MapElementKind::PURPLECHEST => "PURPLECHEST",
        MapElementKind::SPECROCK => "SPECROCK",
        MapElementKind::SUNKENTREASURE => "SUNKENTREASURE",
        MapElementKind::BUMPERCAVELEDGE => "BUMPERCAVELEDGE",
        MapElementKind::CATFISH => "CATFISH",
        MapElementKind::DIGGAME => "DIGGAME",
        MapElementKind::STUMPY => "STUMPY",
        MapElementKind::FLUTESPOT => "FLUTESPOT",
        MapElementKind::PYRAMID => "PYRAMID",
    }
}

pub fn kind_to_source(kind: MapElementKind) -> ImageSource<'static> {
    match kind {
        MapElementKind::ENTRANCE => egui::include_image!("../assets/entrance.png"),
        MapElementKind::ITEM => egui::include_image!("../assets/item.png"),
        MapElementKind::ZELDA => egui::include_image!("../assets/icons/dungeons/maiden.png"),
        MapElementKind::HCL => egui::include_image!("../assets/icons/dungeons/hc-l.png"),
        MapElementKind::HCD => egui::include_image!("../assets/icons/dungeons/hc-d.png"),
        MapElementKind::HCR => egui::include_image!("../assets/icons/dungeons/hc-r.png"),
        MapElementKind::EP => egui::include_image!("../assets/icons/dungeons/ep.png"),
        MapElementKind::DPL => egui::include_image!("../assets/icons/dungeons/dp-l.png"),
        MapElementKind::DPD => egui::include_image!("../assets/icons/dungeons/dp-d.png"),
        MapElementKind::DPR => egui::include_image!("../assets/icons/dungeons/dp-r.png"),
        MapElementKind::DPU => egui::include_image!("../assets/icons/dungeons/dp-u.png"),
        MapElementKind::TH => egui::include_image!("../assets/icons/dungeons/th.png"),
        MapElementKind::AT => egui::include_image!("../assets/icons/dungeons/at.png"),
        MapElementKind::PD => egui::include_image!("../assets/icons/dungeons/pd.png"),
        MapElementKind::SP => egui::include_image!("../assets/icons/dungeons/sp.png"),
        MapElementKind::SW => egui::include_image!("../assets/icons/dungeons/sw.png"),
        MapElementKind::TT => egui::include_image!("../assets/icons/dungeons/tt.png"),
        MapElementKind::IP => egui::include_image!("../assets/icons/dungeons/ip.png"),
        MapElementKind::MM => egui::include_image!("../assets/icons/dungeons/mm.png"),
        MapElementKind::TRL => egui::include_image!("../assets/icons/dungeons/tr-l.png"),
        MapElementKind::TRD => egui::include_image!("../assets/icons/dungeons/tr-d.png"),
        MapElementKind::TRR => egui::include_image!("../assets/icons/dungeons/tr-r.png"),
        MapElementKind::TRU => egui::include_image!("../assets/icons/dungeons/tr-u.png"),
        MapElementKind::GT => egui::include_image!("../assets/icons/dungeons/gt.png"),
        MapElementKind::GANON => egui::include_image!("../assets/icons/dungeons/ganon.png"),
        MapElementKind::SPECU => egui::include_image!("../assets/icons/connectors/spec-u.png"),
        MapElementKind::SPECM => egui::include_image!("../assets/icons/connectors/spec-m.png"),
        MapElementKind::SPECL => egui::include_image!("../assets/icons/connectors/spec-l.png"),
        MapElementKind::PARAU => egui::include_image!("../assets/icons/connectors/paradox-u.png"),
        MapElementKind::PARAM => egui::include_image!("../assets/icons/connectors/paradox-m.png"),
        MapElementKind::PARAL => egui::include_image!("../assets/icons/connectors/paradox-l.png"),
        MapElementKind::DARK => egui::include_image!("../assets/icons/connectors/dark-cave.png"),
        MapElementKind::RESCUE => egui::include_image!("../assets/icons/connectors/rescue-cave.png"),
        MapElementKind::DESCENT => egui::include_image!("../assets/icons/connectors/descent-cave.png"),
        MapElementKind::OLDMANU => egui::include_image!("../assets/icons/connectors/oldman-u.png"),
        MapElementKind::OLDMANL => egui::include_image!("../assets/icons/connectors/oldman-l.png"),
        MapElementKind::FAIRY => egui::include_image!("../assets/icons/connectors/fairy-cave.png"),
        MapElementKind::SUPERBUNNYU => egui::include_image!("../assets/icons/connectors/bunny-u.png"),
        MapElementKind::SUPERBUNNYL => egui::include_image!("../assets/icons/connectors/bunny-l.png"),
        MapElementKind::BROTHERS => egui::include_image!("../assets/icons/connectors/brothers.png"),
        MapElementKind::BUMPERU => egui::include_image!("../assets/icons/connectors/bumper-u.png"),
        MapElementKind::BUMPERL => egui::include_image!("../assets/icons/connectors/bumper-l.png"),
        MapElementKind::ELDER => egui::include_image!("../assets/icons/connectors/elder.png"),
        MapElementKind::SPIRALU => egui::include_image!("../assets/icons/connectors/spiral-u.png"),
        MapElementKind::SPIRALL => egui::include_image!("../assets/icons/connectors/spiral-l.png"),
        MapElementKind::HOOKSHOT => egui::include_image!("../assets/icons/connectors/hookshot.png"),
        MapElementKind::HYPE => egui::include_image!("../assets/icons/entrances/hypecave.png"),
        MapElementKind::MMC => egui::include_image!("../assets/icons/entrances/minimoldorm.png"),
        MapElementKind::BLINDS => egui::include_image!("../assets/icons/entrances/blind.png"),
        MapElementKind::MIRESHED => egui::include_image!("../assets/icons/entrances/mireshed.png"),
        MapElementKind::WATERFALL => egui::include_image!("../assets/icons/entrances/waterfall.png"),
        MapElementKind::PFAIRY => egui::include_image!("../assets/icons/entrances/pyramid.png"),
        MapElementKind::LIBRARY => egui::include_image!("../assets/icons/entrances/library.png"),
        MapElementKind::MIMIC => egui::include_image!("../assets/icons/entrances/mimic.png"),
        MapElementKind::SPIKE => egui::include_image!("../assets/icons/entrances/spike.png"),
        MapElementKind::SICKKID => egui::include_image!("../assets/icons/entrances/sickkid.png"),
        MapElementKind::CHESTGAME => egui::include_image!("../assets/icons/entrances/chestgame.png"),
        MapElementKind::CAVE45 => egui::include_image!("../assets/icons/entrances/cave45.png"),
        MapElementKind::AGINAH => egui::include_image!("../assets/icons/entrances/aginah.png"),
        MapElementKind::CHICKEN => egui::include_image!("../assets/icons/entrances/chicken.png"),
        MapElementKind::GYL => egui::include_image!("../assets/icons/entrances/graveyardledge.png"),
        MapElementKind::DAM => egui::include_image!("../assets/icons/entrances/dam.png"),
        MapElementKind::BONK => egui::include_image!("../assets/icons/entrances/bonkrocks.png"),
        MapElementKind::CHOUSE => egui::include_image!("../assets/icons/entrances/chouse.png"),
        MapElementKind::ICEROD => egui::include_image!("../assets/icons/entrances/icerod.png"),
        MapElementKind::BREWERY => egui::include_image!("../assets/icons/entrances/brewery.png"),
        MapElementKind::KINGSTOMB => egui::include_image!("../assets/icons/entrances/kingstomb.png"),
        MapElementKind::HAMMERPEGS => egui::include_image!("../assets/icons/entrances/hammerpegs.png"),
        MapElementKind::CHECKERBOARD => egui::include_image!("../assets/icons/entrances/checkerboard.png"),
        MapElementKind::SAHA => egui::include_image!("../assets/icons/entrances/saha.png"),
        MapElementKind::SMITH => egui::include_image!("../assets/icons/entrances/smith.png"),
        MapElementKind::REDBOMB => egui::include_image!("../assets/icons/entrances/bigbomb.png"),
        MapElementKind::POTION => egui::include_image!("../assets/icons/entrances/potionshop.png"),
        MapElementKind::UPGRADEFAIRY => egui::include_image!("../assets/icons/entrances/luckfairy.png"),
        MapElementKind::SHOP => egui::include_image!("../assets/icons/entrances/rupee.png"),
        MapElementKind::BOOTS => egui::include_image!("../assets/icons/items/boots.png"),
        MapElementKind::MIRROR => egui::include_image!("../assets/icons/items/mirror.png"),
        MapElementKind::MEARL => egui::include_image!("../assets/icons/items/mearl.png"),
        MapElementKind::GLOVE => egui::include_image!("../assets/icons/items/glove.png"),
        MapElementKind::HAMMER => egui::include_image!("../assets/icons/items/hammer.png"),
        MapElementKind::FIREROD => egui::include_image!("../assets/icons/items/firerod.png"),
        MapElementKind::FLIPPERS => egui::include_image!("../assets/icons/items/flippers.png"),
        MapElementKind::BOW => egui::include_image!("../assets/icons/items/bow.png"),
        MapElementKind::LAMP => egui::include_image!("../assets/icons/items/lamp.png"),
        MapElementKind::SWORD => egui::include_image!("../assets/icons/items/sword.png"),
        MapElementKind::BOMBOS => egui::include_image!("../assets/icons/items/bombos.png"),
        MapElementKind::SOMARIA => egui::include_image!("../assets/icons/items/somaria.png"),
        MapElementKind::POWDER => egui::include_image!("../assets/icons/items/powder.png"),
        MapElementKind::BIGKEY => egui::include_image!("../assets/icons/items/bigkey.png"),
        MapElementKind::SMALLKEY => egui::include_image!("../assets/icons/items/smallkey.png"),
        MapElementKind::BLANK => egui::include_image!("../assets/icons/blank.png"),
        MapElementKind::BOMBOSTABLET => egui::include_image!("../assets/item.png"),
        MapElementKind::ETHERTABLET => egui::include_image!("../assets/item.png"),
        MapElementKind::BOTTLEMERCHANT => egui::include_image!("../assets/item.png"),
        MapElementKind::DESERTLEDGE => egui::include_image!("../assets/item.png"),
        MapElementKind::FLOATINGISLAND => egui::include_image!("../assets/item.png"),
        MapElementKind::HOBO => egui::include_image!("../assets/item.png"),
        MapElementKind::KINGZORA => egui::include_image!("../assets/item.png"),
        MapElementKind::ZORALEDGE => egui::include_image!("../assets/item.png"),
        MapElementKind::LAKEHYLIAISLAND => egui::include_image!("../assets/item.png"),
        MapElementKind::PED => egui::include_image!("../assets/item.png"),
        MapElementKind::MAZERACE => egui::include_image!("../assets/item.png"),
        MapElementKind::MUSHROOM => egui::include_image!("../assets/item.png"),
        MapElementKind::OLDMAN => egui::include_image!("../assets/item.png"),
        MapElementKind::PURPLECHEST => egui::include_image!("../assets/item.png"),
        MapElementKind::SPECROCK => egui::include_image!("../assets/item.png"),
        MapElementKind::SUNKENTREASURE => egui::include_image!("../assets/item.png"),
        MapElementKind::BUMPERCAVELEDGE => egui::include_image!("../assets/item.png"),
        MapElementKind::CATFISH => egui::include_image!("../assets/item.png"),
        MapElementKind::DIGGAME => egui::include_image!("../assets/item.png"),
        MapElementKind::STUMPY => egui::include_image!("../assets/item.png"),
        MapElementKind::FLUTESPOT => egui::include_image!("../assets/item.png"),
        MapElementKind::PYRAMID => egui::include_image!("../assets/item.png"),
    }
}

#[allow(unused)]
pub fn kind_to_category(kind: &MapElementKind) -> MapElementCategory {
    match kind {
        MapElementKind::ENTRANCE => MapElementCategory::BLANK,
        MapElementKind::ITEM => MapElementCategory::BLANK,
        MapElementKind::ZELDA => MapElementCategory::HC,
        MapElementKind::HCL => MapElementCategory::HC,
        MapElementKind::HCD => MapElementCategory::HC,
        MapElementKind::HCR => MapElementCategory::HC,
        MapElementKind::EP => MapElementCategory::EP,
        MapElementKind::DPL => MapElementCategory::DP,
        MapElementKind::DPD => MapElementCategory::DP,
        MapElementKind::DPR => MapElementCategory::DP,
        MapElementKind::DPU => MapElementCategory::DP,
        MapElementKind::TH => MapElementCategory::TH,
        MapElementKind::AT => MapElementCategory::AT,
        MapElementKind::PD => MapElementCategory::PD,
        MapElementKind::SP => MapElementCategory::SP,
        MapElementKind::SW => MapElementCategory::SW,
        MapElementKind::TT => MapElementCategory::TT,
        MapElementKind::IP => MapElementCategory::IP,
        MapElementKind::MM => MapElementCategory::MM,
        MapElementKind::TRL => MapElementCategory::TR,
        MapElementKind::TRD => MapElementCategory::TR,
        MapElementKind::TRR => MapElementCategory::TR,
        MapElementKind::TRU => MapElementCategory::TR,
        MapElementKind::GT => MapElementCategory::GT,
        MapElementKind::GANON => MapElementCategory::GANON,
        MapElementKind::SPECU => MapElementCategory::SPEC,
        MapElementKind::SPECM => MapElementCategory::SPEC,
        MapElementKind::SPECL => MapElementCategory::SPEC,
        MapElementKind::PARAU => MapElementCategory::PARA,
        MapElementKind::PARAM => MapElementCategory::PARA,
        MapElementKind::PARAL => MapElementCategory::PARA,
        MapElementKind::DARK => MapElementCategory::DARKCAVE,
        MapElementKind::RESCUE => MapElementCategory::DARKCAVE,
        MapElementKind::DESCENT => MapElementCategory::DARKCAVE,
        MapElementKind::OLDMANU => MapElementCategory::OLDMAN,
        MapElementKind::OLDMANL => MapElementCategory::OLDMAN,
        MapElementKind::FAIRY => MapElementCategory::FAIRY,
        MapElementKind::SUPERBUNNYU => MapElementCategory::SUPERBUNNY,
        MapElementKind::SUPERBUNNYL => MapElementCategory::SUPERBUNNY,
        MapElementKind::BROTHERS => MapElementCategory::BROTHERS,
        MapElementKind::BUMPERU => MapElementCategory::BUMPER,
        MapElementKind::BUMPERL => MapElementCategory::BUMPER,
        MapElementKind::ELDER => MapElementCategory::ELDER,
        MapElementKind::SPIRALU => MapElementCategory::SPIRAL,
        MapElementKind::SPIRALL => MapElementCategory::SPIRAL,
        MapElementKind::HOOKSHOT => MapElementCategory::HOOKSHOT,
        MapElementKind::HYPE => MapElementCategory::HYPE,
        MapElementKind::MMC => MapElementCategory::MMC,
        MapElementKind::BLINDS => MapElementCategory::BLINDS,
        MapElementKind::MIRESHED => MapElementCategory::MIRESHED,
        MapElementKind::WATERFALL => MapElementCategory::WATERFALL,
        MapElementKind::PFAIRY => MapElementCategory::PFAIRY,
        MapElementKind::LIBRARY => MapElementCategory::LIBRARY,
        MapElementKind::MIMIC => MapElementCategory::MIMIC,
        MapElementKind::SPIKE => MapElementCategory::SPIKE,
        MapElementKind::SICKKID => MapElementCategory::SICKKID,
        MapElementKind::CHESTGAME => MapElementCategory::CHESTGAME,
        MapElementKind::CAVE45 => MapElementCategory::CAVE45,
        MapElementKind::AGINAH => MapElementCategory::AGINAH,
        MapElementKind::CHICKEN => MapElementCategory::CHICKEN,
        MapElementKind::GYL => MapElementCategory::GYL,
        MapElementKind::DAM => MapElementCategory::DAM,
        MapElementKind::BONK => MapElementCategory::BONK,
        MapElementKind::CHOUSE => MapElementCategory::CHOUSE,
        MapElementKind::ICEROD => MapElementCategory::ICEROD,
        MapElementKind::BREWERY => MapElementCategory::BREWERY,
        MapElementKind::KINGSTOMB => MapElementCategory::KINGSTOMB,
        MapElementKind::HAMMERPEGS => MapElementCategory::HAMMERPEGS,
        MapElementKind::CHECKERBOARD => MapElementCategory::CHECKERBOARD,
        MapElementKind::SAHA => MapElementCategory::SAHA,
        MapElementKind::SMITH => MapElementCategory::SMITH,
        MapElementKind::REDBOMB => MapElementCategory::REDBOMB,
        MapElementKind::POTION => MapElementCategory::POTION,
        MapElementKind::UPGRADEFAIRY => MapElementCategory::UPGRADEFAIRY,
        MapElementKind::SHOP => MapElementCategory::SHOP,
        MapElementKind::BOOTS => MapElementCategory::BOOTS,
        MapElementKind::MIRROR => MapElementCategory::MIRROR,
        MapElementKind::MEARL => MapElementCategory::MEARL,
        MapElementKind::GLOVE => MapElementCategory::GLOVE,
        MapElementKind::HAMMER => MapElementCategory::HAMMER,
        MapElementKind::FIREROD => MapElementCategory::FIREROD,
        MapElementKind::FLIPPERS => MapElementCategory::FLIPPERS,
        MapElementKind::BOW => MapElementCategory::BOW,
        MapElementKind::LAMP => MapElementCategory::LAMP,
        MapElementKind::SWORD => MapElementCategory::SWORD,
        MapElementKind::BOMBOS => MapElementCategory::BOMBOS,
        MapElementKind::SOMARIA => MapElementCategory::SOMARIA,
        MapElementKind::POWDER => MapElementCategory::POWDER,
        MapElementKind::BIGKEY => MapElementCategory::BIGKEY,
        MapElementKind::SMALLKEY => MapElementCategory::SMALLKEY,
        MapElementKind::BLANK => MapElementCategory::BLANK,
        MapElementKind::BOMBOSTABLET => MapElementCategory::BLANK,
        MapElementKind::ETHERTABLET => MapElementCategory::BLANK,
        MapElementKind::BOTTLEMERCHANT => MapElementCategory::BLANK,
        MapElementKind::DESERTLEDGE => MapElementCategory::BLANK,
        MapElementKind::FLOATINGISLAND => MapElementCategory::BLANK,
        MapElementKind::HOBO => MapElementCategory::BLANK,
        MapElementKind::KINGZORA => MapElementCategory::BLANK,
        MapElementKind::ZORALEDGE => MapElementCategory::BLANK,
        MapElementKind::LAKEHYLIAISLAND => MapElementCategory::BLANK,
        MapElementKind::PED => MapElementCategory::BLANK,
        MapElementKind::MAZERACE => MapElementCategory::BLANK,
        MapElementKind::MUSHROOM => MapElementCategory::BLANK,
        MapElementKind::OLDMAN => MapElementCategory::BLANK,
        MapElementKind::PURPLECHEST => MapElementCategory::BLANK,
        MapElementKind::SPECROCK => MapElementCategory::BLANK,
        MapElementKind::SUNKENTREASURE => MapElementCategory::BLANK,
        MapElementKind::BUMPERCAVELEDGE => MapElementCategory::BLANK,
        MapElementKind::CATFISH => MapElementCategory::BLANK,
        MapElementKind::DIGGAME => MapElementCategory::BLANK,
        MapElementKind::STUMPY => MapElementCategory::BLANK,
        MapElementKind::FLUTESPOT => MapElementCategory::BLANK,
        MapElementKind::PYRAMID => MapElementCategory::BLANK,
    }
}

pub fn map_element_kind_to_map_element(kind: MapElementKind) -> MapElement {
    return MapElement {
        pos: Pos2::new(0.0, 0.0),
        size: None, 
        kind: kind,
        id: Uuid::new_v4(),
        checked: false
    }
}

pub fn kind_is_dragable(kind: MapElementKind) -> bool {
    return kind != MapElementKind::ENTRANCE && kind != MapElementKind::ITEM
}